import React, { Component } from 'react';

class Header extends Component {
    render() {
        return (
            <div className="page-info">
                <h1>Heat Grid Simulator</h1>
                <h2>React</h2>
                <h3>Overview</h3>
                <p>The <strong>Heat Grid</strong> is comprised of a square of cells. Each cell has its own temperature.
                    The cells you select will get hotter by having heat added to them so that their temperature will increase by 1 degree each heat interval.
                    Additionally, during each heat interval, heat is transferred from hot cells to each neighboring cell, disappating outward.
                    For example, if all cells are at 0 degrees and you turn on a center cell, during the first heat interval,
                    the 1 degree of heat generated by that cell will be spread equally throughout the selected cell and also the eight neighboring cells.
                    Each of these nine cells would then have 1/9 of a degree (0.111).
                </p>
                <p>Note that heat dissipates and is lost off the edge of the grid.</p>
                <p>As the heat for a particular cell increases, its background color changes. For this color pattern I mimicked the heat colors which actually occur when <a href="http://www.blksmth.com/heat_colors.htm">mild steel</a> is heated.</p>
                <p>Heat Grid Simulator is a useful coding challenge for learning front end frameworks. This was developed first in <a href="../heat-grid-js/">vanilla JavaScript</a>,
                    next using React, and finally using <a href="../heat-grid-js/">Angular</a>.</p>
                <h3>How to Use Heat Grid Simulator</h3>
                <p>Click/tap on a cell (a square in the grid below) to select it and add one degree of heat to that cell per heat interval.
                    (Selected cells are indicated by red borders.) You have the option to heat as many or as few of the cells as you like.</p>
                <p>The "Turn All On" and "Turn All Off" buttons are quick and easy ways to see the Heat Grid Simulator in action.</p>
            </div>
        );
    }
}

export default Header;

